[package]
name = "async_ecs"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "6.0.1"
anyhow = "1.0.86"
thiserror = "1.0.63"
parking_lot = { version = "0.12.3", features = ["send_guard"] }
tokio = { version = "1.39.2", features = ["full"] }