[package]
name = "async_ecs"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "6.0.1"
anyhow = "1.0.86"
thiserror = "1.0.63"
tokio = { version = "1.39.2", features = ["full"] }
futures = "0.3.30"
rayon = "1.10.0"