[package]
name = "nbt-lib"
version = "0.1.0"
edition = "2021"

[features]
derive = ["nbt-derive"]

[dependencies]
nbt-derive = { path = "../nbt-derive", optional = true }
thiserror = "1.0.63"
ferrumc_codec = { path = "../../ferurmc_codec" }
tokio = { version = "1.16.1", features = ["io-util"] }

[dev-dependencies]
nbt-derive = { path = "../nbt-derive" }

[lib]