[package]
name = "nbt-lib"
version = "0.1.0"
edition = "2021"

[features]
derive = ["nbt-derive"]

[dependencies]
nbt-derive = { path = "../nbt-derive", optional = true }
thiserror = "1.0.63"


[dev-dependencies]
nbt-derive = { path = "../nbt-derive" }

[lib]