[package]
name = "ferrumc-api"
description = "FerrumC Mod API - Core traits for creating mods"
edition.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
# Core dependencies for API traits
bevy_ecs = { workspace = true }
thiserror = { workspace = true }
ferrumc-commands = { path = "../commands" }
ferrumc-world = { path = "../world" }
