[workspace]
resolver = "2"

members = [
    "crates/bin",
    "crates/lib/*",
]
exclude = []

# Strip debuginfo from the release builds
# Also enable thin LTO for some optimizations
[profile.release]
strip = "debuginfo"
lto = "thin"
opt-level = "z"

# A little bit of a speedup
[profile.dev]
split-debuginfo = "unpacked"
