[package]
name = "ferrumc2_0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Async
tokio = {version = "1.38.0", features = ["full"]}

# Error handling
anyhow = "1.0.86"
thiserror = "1.0.61"

# Logging
log = "0.4.21"
env_logger = "0.11.3"

# config / ser / de
serde = { version = "1.0.203", features = ["derive"]}
toml = "0.8.14"
config = "0.14.0"
lazy_static = "1.4.0"

# Custom crates
ferrumc_net = { path = "src/crates/ferrumc_net"}
