# FerrumC Project workspace
#
# Layout of this file:
# - Members of the workspace.
# - Profile compilation settings.
# - Workspace lints
# - Workspace dependencies.


[workspace]
resolver = "2"

#================= Members =================#
members = [
    "src/bin",
    "src/lib/adapters/anvil",
    "src/lib/adapters/anvil",
    "src/lib/adapters/nbt",
    "src/lib/adapters/nbt",
    "src/lib/core",
    "src/lib/core/state",
    "src/lib/derive_macros",
    "src/lib/derive_macros",
    "src/lib/ecs",
    "src/lib/events",
    "src/lib/net",
    "src/lib/net/crates/codec",
    "src/lib/net/crates/encryption",
    "src/lib/plugins",
    "src/lib/storage",
    "src/lib/text",
    "src/lib/utils",
    "src/lib/utils/general_purpose",
    "src/lib/utils/logging",
    "src/lib/utils/profiling",
    "src/lib/world",
    "src/lib/world_gen",
    "src/lib/utils/threadpool",
]

#================== Lints ==================#
[workspace.lints.rust]
unsafe_code = "deny"
unused_unsafe = "deny"
#unsafe_op_in_unsafe_fn = "deny"
#unused_crate_dependencies = "deny"
unused_import_braces = "deny"
unused_lifetimes = "deny"
keyword_idents_2018 = "deny"
keyword_idents_2024 = "deny"
missing_abi = "deny"
future_incompatible = { level = "deny", priority = -1 }

[workspace.lints.clippy]
borrow_as_ptr = "deny"
case_sensitive_file_extension_comparisons = "deny"
cast_lossless = "deny"
cast_ptr_alignment = "deny"
match_bool = "deny"
mut_mut = "deny"
wildcard_dependencies = "deny"
redundant_type_annotations = "deny"
infinite_loop = "deny"

#================= Profile =================#
[profile.profiling]
inherits = "release"
debug = true

[profile.release]

[profile.hyper]
inherits = "release"
strip = "symbols"
lto = true
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
panic = "abort"
codegen-units = 1

#=============== Dependencies ==============#
[workspace.dependencies]
# Workspace members
ferrumc-anvil = { path = "src/lib/adapters/anvil" }
ferrumc-config = { path = "src/lib/utils/config" }
ferrumc-core = { path = "src/lib/core" }
ferrumc-ecs = { path = "src/lib/ecs" }
ferrumc-events = { path = "src/lib/events" }
ferrumc-general-purpose = { path = "src/lib/utils/general_purpose" }
ferrumc-logging = { path = "src/lib/utils/logging" }
ferrumc-macros = { path = "src/lib/derive_macros" }
ferrumc-nbt = { path = "src/lib/adapters/nbt" }
ferrumc-net = { path = "src/lib/net" }
ferrumc-net-codec = { path = "src/lib/net/crates/codec" }
ferrumc-net-encryption = { path = "src/lib/net/crates/encryption" }
ferrumc-plugins = { path = "src/lib/plugins" }
ferrumc-profiling = { path = "src/lib/utils/profiling" }
ferrumc-state = { path = "src/lib/core/state" }
ferrumc-storage = { path = "src/lib/storage" }
ferrumc-text = { path = "src/lib/text" }
ferrumc-utils = { path = "src/lib/utils" }
ferrumc-world = { path = "src/lib/world" }
ferrumc-world-gen = { path = "src/lib/world_gen" }
ferrumc-threadpool = { path = "src/lib/utils/threadpool" }


# Asynchronous
tokio = { version = "1.41.2", features = ["full"] }

# Logging
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing-appender = "0.2.3"
log = "0.4.27"
console-subscriber = "0.4.1"

# Concurrency/Parallelism
parking_lot = "0.12.3"
rayon = "1.10.0"
crossbeam-channel = "0.5.15"
rusty_pool = "0.7.0"
crossbeam-queue = "0.3.12"

# Network
reqwest = { version = "0.12.15", features = ["json"] }
ureq = "3.0.10"

# Error handling
thiserror = "2.0.3"

# Cryptography
rand = "0.9.0-beta.0"
fnv = "1.0.7"
wyhash = "0.5.0"

# Encoding/Serialization
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_derive = "1.0.219"
base64 = "0.22.1"
bitcode = "0.6.6"
bitcode_derive = "0.6.5"
toml = "0.8.20"

# Bit manipulation
byteorder = "1.5.0"

# Data types
dashmap = "6.1.0"
uuid = { version = "1.16", features = ["v4", "v3", "serde"] }

# Macros
lazy_static = "1.5.0"
quote = "1.0.40"
syn = "2.0.100"
proc-macro2 = "1.0.94"
proc-macro-crate = "3.3.0"
paste = "1.0.15"
maplit = "1.0.2"
macro_rules_attribute = "0.2.0"
enum_delegate = "0.2.0"

# Magic ("life-before-main" initialization, __attribute__((constructor)))
ctor = "0.4.1"
dhat = "0.3.3"

# Compression/Decompression
libflate = "2.1.0"
flate2 = { version = "1.1.1", features = ["zlib"], default-features = false }
zstd = { version = "0.13.3" }
brotli = "7.0.0"
lzzzz = "2.0.0"
yazi = "0.2.1"
bzip2 = "0.5.2"

# Database
heed = "0.22.0"
moka = "0.12.10"

# CLI
clap = "4.5.36"
indicatif = "0.17.11"
colored = "3.0.0"

# Misc
deepsize = "0.2.0"
page_size = "0.6.0"
regex = "1.11.1"
noise = "0.9.0"
ctrlc = "3.4.6"

# I/O
memmap2 = "0.9.5"
tempfile = "3.19.1"

# Benchmarking
criterion = { version = "0.5.1", features = ["html_reports"] }
