[package]
name = "ferrumc-net"
description = "Defines and implements all network related functionalities of FerrumC"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.63"
ferrumc-net-encryption = { workspace = true }
ferrumc-net-packets = { workspace = true }