[package]
name = "custom_nbt"
version = "0.1.0"
edition = "2021"

[lib]


[dependencies]
fastnbt = "2.5.0"
serde = { version = "1.0", features = ["derive"] }

[[bench]]
name = "benches"
harness = false


[dev-dependencies.criterion]
version = "0.5.1"
features = ["html_reports"]
