[workspace]
members = [
    "nbt-lib",
    "nbt-derive", "deserializer",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Sweattypalms", "Recore_"]
license = "MIT"

