[package]
name = "profiling"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0-alpha.2"
lazy_static = "1.5.0"
hashbrown = "0.14.5"
dashmap = "6.1.0"
parking_lot = "0.12.3"
tracing-subscriber = "0.3.18"
tracing = "0.1.40"
tinyvec = "1.8.0"
serde = "1.0.210"
serde_json = "1.0.128"
serde_derive = "1.0.210"

logging = { path = "../logging" }
log = "0.4.22"
tokio = { version = "1.40.0", features = ["full"] }
derive_macros = { path = "../../derive_macros" }
