[package]
name = "ferrumc"
description = "A high-performance Minecraft server implementation, crafted in Rust for unparalleled speed and efficiency."
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctor.workspace = true
parking_lot.workspace = true
ferrumc-logging.workspace = true
tracing.workspace = true

[[bin]]
name = "ferrumc"
path = "src/main.rs"
