[package]
name = "ferrumc"
description = "A high-performance Minecraft server implementation, crafted in Rust for unparalleled speed and efficiency."
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = { workspace = true }

ferrumc-core = { workspace = true }
ferrumc-ecs = { workspace = true }
ferrumc-events = { workspace = true }
ferrumc-net = { workspace = true }
ferrumc-net-encryption = { workspace = true }
ferrumc-net-codec = { workspace = true }
ferrumc-plugins = { workspace = true }
ferrumc-storage = { workspace = true }
ferrumc-utils = { workspace = true }
ferrumc-config = { workspace = true }
ferrumc-profiling = { workspace = true }
ferrumc-logging = { workspace = true }
ferrumc-world = { workspace = true }
ferrumc-macros = { workspace = true }
ferrumc-nbt = { workspace = true }
ferrumc-general-purpose = { workspace = true }
ferrumc-state = { workspace = true }
ferrumc-world-gen = { workspace = true }

rayon = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
flate2 = { workspace = true }
ctor = { workspace = true }
rand = { workspace = true }
log = "0.4.22"
dhat = "0.3.3"

[features]
dhat = []

[[bin]]
name = "ferrumc"
path = "src/main.rs"
