[package]
name = "ferrumc-utils"
description = "Collection of utilities for use within FerrumC codebase."
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.63"
ferrumc-logging = { workspace = true }
ferrumc-profiling = { workspace = true }