name: Rust

on:
  push:
    branches: [ "2.0" ]
  pull_request:
    branches: [ "2.0" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # To allow unstable features
    - name: Install Rust nightly
      run: rustup override set nightly
      
    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
